trimmer/sequence_db/urls.py
from django.urls import path, include
from . import views
from django.urls import include, re_path

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogout, name='Logout'),
    path('signup/', views.signup, name='Logout'),
    path('test_lisa/', views.lisa, name='Logout'),
    path('edit_metadata/', views.edit_metadata, name='Edit Metadata'),
    path('add_faq/', views.add_faq, name='Add FAQ'),
    path('edit_faq/<int:pk>/', views.edit_faq, name='Edit FAQ'),
    path('delete_faq/<int:pk>/', views.delete_faq, name='Edit FAQ'),
    path('faq_list/', views.FAQListView, name='Add FAQ'),
    path('', views.main_page, name='main page'),
    re_path(r'^new_query/$', view=views.TrimmerEntryListView, name='sequence_query'),
    path('status/', views.TrimmerStatusListView, name='status'),
    path('fasta_re/', views.fasta_file_response, name='fasta'),
    path('faq/', views.faq_view, name='faq'),
    path('blat/<str:query_seq>/', views.blat, name='Blat'),
    path('new_entry/<int:pk>/', views.TrimmerEntryDetailView.as_view(), name='sequence_entry'),
    path('new_entry/<int:pk>/<int:pk2>/', views.TrimmerEntryDetailView.as_view(), name='sequence_entry'),
    path('query/', views.SequenceListView, name='sequence_entry'),
    # path('analytics/', views.analytics_view, name='analytics'),
    path('api/entry_list/', views.APIEntryListView.as_view()),
    path('api/status_list/', views.APIStatusListView.as_view()),
    path('csv/status_list/', views.StatusCSVExportView.as_view()),
    path('accounts/profile/', views.main_page, name='Main Page'),
    # path('plate_summary/', views.summary_plate_view, name='Plate Summary'),

]

trimmer/trimmer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import *
from sequence_db import views
from rest_framework import routers


#
# router = routers.DefaultRouter()
# router.register(r'albums', views.AlbumViewSet)


urlpatterns = [
      path(r'', include('sequence_db.urls')),
      path('admin/', admin.site.urls),
] + static(STATIC_URL, document_root=STATIC_ROOT)

trimmer/sequence_db/forms.py
from django import forms
from django.views.generic.edit import FormView, ModelFormMixin
from .models import *
from django import forms
from django.forms import ModelForm, Textarea
from django.db.models.fields import PositiveIntegerField
from .models import *
from django import forms
from .validators import validate_file_extension
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class Blat(forms.Form):
    sequence = forms.CharField(max_length=1000, required=True, widget=forms.Textarea(attrs={"rows": 10, "cols": 100}))
    type = forms.ChoiceField(required=True, choices=(("dna", "DNA"), ("protein","Protein")), initial='DNA')
    search_prefix = forms.CharField(max_length=20, required=False, label="mAb ID Filter")
    clonality = forms.ChoiceField(required=False, choices=(("", ""),("Monoclonal", "Monoclonal"),
                                                          ("Oligoclonal","Oligoclonal")), initial='Monoclonal')


class GeneralFileForm(forms.Form):
    general_file = forms.FileField(required=True, validators=[validate_file_extension])


class AddFAQ(forms.Form):
    question = forms.CharField(max_length=4000, required=True, widget=forms.Textarea(attrs={"rows":5, "cols":100, "width": "100%"}))

    message = forms.CharField(max_length=4000, required=True, widget=forms.Textarea(attrs={"rows":5, "cols":100}))
    is_definition = forms.BooleanField(required=False, initial=False)

    # message = forms.

    class Meta:
        model = FAQ
        fields = ('question','message','is_definition')


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class LISAForm(forms.Form):
    pos_control1 = forms.ChoiceField(required=True, choices=(("A1", "A1"),
                                                     ("A12", "A12"),
                                                     ("H1", "H1"),
                                                     ("H12", "H12")), initial='A1')

    pos_control2 = forms.ChoiceField(required=True, choices=(("A1", "A1"),
                                                     ("A12", "A12"),
                                                     ("H1", "H1"),
                                                     ("H12", "H12")), initial='A12')

    neg_control1 = forms.ChoiceField(required=True, choices=(("A1", "A1"),
                                                     ("A12", "A12"),
                                                     ("H1", "H1"),
                                                     ("H12", "H12")), initial='H1')

    neg_control2 = forms.ChoiceField(required=True, choices=(("A1", "A1"),
                                                     ("A12", "A12"),
                                                     ("H1", "H1"),
                                                     ("H12", "H12")), initial='H12')
    elisa_reduced_xml = forms.FileField(required=True)
    flisa_raw_xml = forms.FileField(required=True)

trimmer/sequence_db/views.py
from django.template import loader
from django.forms import ModelForm
from .models import *
from django.views.generic import DetailView, ListView
from django.views.generic.edit import UpdateView, CreateView, FormMixin

from .filters import *
from .forms import *
import pandas as pd
import plotly.offline as opy
import plotly.graph_objs as go
from .methods import *
from django.shortcuts import render, redirect
from django.conf import settings
import urllib
import json
import plotly.express as px

from django.views.generic import View
import csv
from Bio import SearchIO
import random
import string
import subprocess
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required

# API STUFF
from django.http import HttpResponse, JsonResponse, QueryDict
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .serializers import *
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import generics
from rest_framework import viewsets
from .methods import *
from rest_framework import filters

from django.contrib.auth import login, authenticate, logout
import plotly.express as px
import urllib
import json
from .forms import *
from django.utils.decorators import method_decorator
from django.db.models import Count
from .methods import *
from django.db.models import Q

import xmltodict
import pandas as pd
import numpy as np
import plotly.io as pio
import collections
import pandas as pd


def get_random_string(length):
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str


# def summary_plate_view(request):
#     all = TrimmerSequence.objects.all().values('plate').annotate(total=Count('plate')).order_by('total')
#     for item in all:
#         print(item)
#
#     count_dict = {}
#     seqs = TrimmerSequence.objects.all()
#     for seq in seqs:
#         if seq.plate in count_dict.keys():
#             if seq.entry.mabid in count_dict[seq.plate].keys():# and seq.entry.show_on_web is True:
#                 count_dict[seq.plate][seq.entry.mabid]+=1
#             else: #if seq.entry.show_on_web is True:
#                 count_dict[seq.plate][seq.entry.mabid]=1
#         else:
#             count_dict[seq.plate] = {}
#     sum = 0
#     for key in count_dict.keys():
#         print(key + ' ' + str(len(count_dict[key].keys())))
#         sum +=  len(count_dict[key].keys())
#
#     print("TOTAL MABIDS: " + str(sum))
#


class MyLoginView(auth_views.LoginView):
    # ratelimit_key = 'ip'
    # ratelimit_rate = '10/h'
    # ratelimit_block = True


    def form_valid(self, form):
        request_body = self.request.POST
        if not request_body:
            return None

        ''' Begin reCAPTCHA validation '''
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if result['success'] and user is not None:
            return super().form_valid(form)
        else:
            return redirect('login')



def signup(request):
    context = {}
    if request.method == 'POST':
        main_form = SignUpForm(request.POST)

        ''' Begin reCAPTCHA validation '''

        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())

        ''' End reCAPTCHA validation '''
        if result['success']:
            if main_form.is_valid():
                main_form.save()
                username = main_form.cleaned_data.get('username')
                raw_password = main_form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect("Main Page")
            else:
                context['errors'] = main_form.errors
                context['main_form'] = SignUpForm(request.POST)
        else:
            context['main_form'] = SignUpForm(request.POST)
    else:
        context['main_form'] = SignUpForm()

    return render(request, 'registration/signup.html', context)


def FAQListView(request):

    context= {}
    context['questions'] = FAQ.objects.filter(is_definition=False)
    context['definitions'] = FAQ.objects.filter(is_definition=True)

    return render(request, 'faq_list.html', context)


def MyLogout(request):
    logout(request)
    return redirect('/')


# TODO fix this so to filter pos and neg from Light and Heavy
def main_page(request):
    html = 'home.html'
    context = {}
    all_entries = TrimmerEntry.objects.filter(show_on_web=True)
    all_entries = all_entries.exclude(mabid__contains='positive')
    all_entries = all_entries.exclude(mabid__contains='negative')
    context['total_number_entries'] = len(all_entries)
    context['total_number_light'] = len(TrimmerSequence.objects.filter(chain="Light",
                                                                       anarci_bad=False,
                                                                       anarci_duplicate=False,
                                                                       bad_support=False,
                                                                       entry__show_on_web=True
                                                                       ))
    context['total_number_heavy'] = len(TrimmerSequence.objects.filter(chain="Heavy",
                                                                       anarci_bad=False,
                                                                       anarci_duplicate=False,
                                                                       bad_support=False,
                                                                       entry__show_on_web=True
                                                                       ))

    context['monoclonal_number_entries'] = len(all_entries.filter(~Q(category__in=[4,5])))
    context['monoclonal_number_light'] = len(TrimmerSequence.objects.filter(chain="Light",
                                                                            anarci_bad=False,
                                                                            bad_support=False,
                                                                            anarci_duplicate=False,
                                                                            entry__show_on_web=True).exclude(entry__category__in=[4,5]))
    context['monoclonal_number_heavy'] = len(TrimmerSequence.objects.filter(chain="Heavy",
                                                                            anarci_bad=False,
                                                                            bad_support=False,
                                                                            anarci_duplicate=False,
                                                                            entry__show_on_web=True).exclude(entry__category__in=[4,5]))

    context['parental_number_entries'] = len(all_entries.filter(category__in=[4,5]))
    context['parental_number_light'] = len(TrimmerSequence.objects.filter(chain="Light",
                                                                          entry__category__in=[4,5],
                                                                          anarci_bad=False,
                                                                          bad_support=False,
                                                                          anarci_duplicate=False))
    context['parental_number_heavy'] = len(TrimmerSequence.objects.filter(chain="Heavy",
                                                                          entry__category__in=[4,5],
                                                                          anarci_bad=False,
                                                                          anarci_duplicate=False,
                                                                          bad_support=False,
                                                                          ))

    template = loader.get_template(html)
    return HttpResponse(template.render(context, request))


@staff_member_required
def edit_metadata(request):
    context = {}
    if request.method == 'POST':
        if 'general_file_form' in request.POST:
            form = GeneralFileForm(request.POST, request.FILES)
            if form.is_valid():
                file_path = form.cleaned_data['general_file'].file.name
                metadata_file_process(context, file_path)
            else:
                context['errors'] = form.errors

    context['form'] = GeneralFileForm()
    return render(request, 'edit_metadata.html', context)



@staff_member_required
def add_faq(request):
    if request.method == 'POST':
        form = AddFAQ(request.POST)
        if form.is_valid():
            message = form.cleaned_data['message']
            question = form.cleaned_data['question']

trimmer/sequence_db/templates/add_addgene_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

trimmer/sequence_db/templates/blat.html
{% extends 'base.html' %}


<!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
<!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>-->

{% load crispy_forms_tags %}
{% block content %}
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 50%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;

}

#id_sequence {
    width: 100%;
    height: 200px;
}

</style>

<!-- Datatables stuff -->
<!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.17/css/jquery.dataTables.css">-->
<!--<script src="https://code.jquery.com/jquery-1.9.1.js"></script>-->
<!--<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.17/js/jquery.dataTables.js"></script>-->

<!--<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>-->
<!--<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/responsive/1.0.7/js/dataTables.responsive.min.js"></script>-->


<!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">-->
<!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/1.0.7/css/responsive.dataTables.min.css">-->


{% load static %}
<link rel="stylesheet" href="{% static "css/jquery.dataTables.css" %}">
<link rel="stylesheet" href="{% static "css/jquery.dataTables.min.css" %}">
<link rel="stylesheet" href="{% static "css/responsive.dataTables.min.css" %}">
<script src="{% static "js/jquery-1.9.1.js" %}"></script>
<script src="{% static "js/jquery.dataTables.js" %}"></script>
<script src="{% static "js/jquery.dataTables.min.js" %}"></script>
<script src="{% static "js/dataTables.responsive.min.js" %}"></script>
<script src="{% static "js/jquery.dataTables.js" %}"></script>



<script>




$(document).ready(function(){ $('#myTable').DataTable(); });

$(document).ready( function () {
  var table = $('#example').DataTable({
      "order": [[ 1, 'desc' ], [ 0, 'desc' ]]

  });
} );

$(document).ready(function() {
    $('#example1').DataTable({"pageLength": 50, searching: false, paging: false, info: false, ordering: false});
} );


</script>
<div class="w3-container w3-content w3-padding-16">
    <div class="well" style="background-color:EAEAEA;padding:10;border-radius:8px;">

              {% if errors %}
                    {% for error in errors %}
                        {% if error %}
                            <div class="alert alert-danger">
                                <strong> Entry {{forloop.counter}}: {{ error|escape }}</strong>
                            </div>
                        {% endif %}
                    {% endfor %}
              {% endif %}
              {% if err %}
                            <div class="alert alert-danger">
                                <strong> Entry {{forloop.counter}}: {{ err|escape }}</strong>
                            </div>
              {% endif %}

              {% if out %}
                            <div>
                                <strong> Entry {{forloop.counter}}: {{ out|escape }}</strong>
                            </div>
              {% endif %}
              {% if prefix %}
                            <div class="alert">
                                <strong> Entry {{forloop.counter}}: {{ prefix|escape }}</strong>
                            </div>
              {% endif %}
    <h2>BLAT Search</h2>
      <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
<!--                <script src='https://www.google.com/recaptcha/api.js'></script>-->
<!--                <div style="padding:20px" class="g-recaptcha" data-sitekey="6LfwjbEZAAAAAHMfs22TYLtJw5YWx-EsglR1LsQo"></div>-->
          <div style="padding-top:20px">

            <button type="submit" class="btn btn-success" >Submit</button>

          </div>
      </form>
    </div>
</div>

  <div class="w3-container w3-content w3-center w3-padding-5" style="max-width:10000px">
  <h2>Query Results</h2>
        <table id="example" class="display responsive nowrap" cellspacing="0" width="100%" align="center">
              <thead>
                <tr>
                    <th>Percent Identity</th>
                    <th>Score</th>
                    <th>Mab ID</th>
                    <th>Plate Well</th>
                    <th>Chain Type</th>
                    <th>Clonality</th>
                    <th>See Entry</th>

                </tr>
              </thead>
          <tbody>
          {% for item in queryset %}
              <tr>
                  <td>{{item.ident_pct}}</td>
                  <td>{{item.score}}</td>
                  <td>{{item.mabid}}</td>
                  <td>{{item.plate_well}}</td>
                  {% if item.chain %}
                    <td>{{item.chain}}</td>
                  {% else %}
                    <td></td>
                  {% endif %}
                  <td>{{item.clonality}}</td>
                  {% if item.pk %}
                  <td>
                    <a href="/new_entry/{{item.entry_pk}}/{{item.pk}}">
                      <button  label="Entry Details" name="so_link" class="btn btn-info">See Full Entry</button>
                    </a>
                  </td>
                   {% else %}
                  <td></td>
                  {% endif %}
              </tr>
          {% empty %}
           <div>No invoices yet.</div>
          {% endfor %}
           </tbody>
        </table>
</div>

{% endblock %}

trimmer/sequence_db/templates/entry.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:46px">

  <!-- Automatic Slideshow Images -->
  <!--<div class="mySlides w3-display-container w3-center">-->
    <!--<img src="https://bioinformatics.uconn.edu/wp-content/uploads/sites/15/2013/06/bioinfo3.png" style="width:100%">-->
  <!--</div>-->
  <!--<div class="mySlides w3-display-container w3-center">-->
    <!--<img src="https://lh3.googleusercontent.com/ECEa_XenJr0Lv8AGMKOXtyu81br8vx7nZTqsZmgrJ_oF9w1yZlFqjR1TOM_s-wZO5fpfhYpo7sBV0jD6_hTJs8yoxoXfD4DZRBBQ0dhQI-pArhqO7ieJSPGXQPLF6YoR3rG8o6c71DIEGh-1gvFQSc3FCVcddXL_Sf7H_GjdNpSRQqr2L5b3RWptVH9LPT1w2GFzKnsXs-MZEtqccU4TWB7npVlugyWbClvF5AThjyiQQ1aBd8Qax2Z6qEX4wM3Yb4fyEqkilQbP9Kegsl0swZ4IYXO047kYZUCquRahzz-yOqfmbihiFKOnPhba8wymribbWk-htA0hVN8UNQxMIYxsaQkAGcFVVF-OEc4Z7d0BB2B7CQ51qmvu52Di0EXkh8P0cEIBKst7BrYERapq6JRbfNstLyroSO_4SmAO2kxO0wmA0CFPPRU9ooahovgciyeIz9pSwJRGV7i3ZzPyuXnapE-_rSzgJYhY4Dz6Zmhr7e48HL8R7VCBXmUxvJtZVEuejzC9KLU14fTNq47-8knwkAlJVI0xkrSvRqQraITm8T_RNekjzjUR-WRWyDZRPNr_ryywr-pP7wbybKqYYeCNV-V95pxkTM4MLyonLX-AwXJx1aX026NP67GCOuoem0aH7xy9zteOn1Yo2f9GMU-oRHGR-uLk9Ig1qg86fafobXx_HphzR4jEnvSn4dzSj2kwm2q54BVuf2IWOA=w1395-h1860-no" style="width:20%">-->
  <!--</div>-->

</div>

  <!-- The Header Bio Section -->
  <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="about_me">
    <h2 class="w3-wide" align="left">Entry {{entry.name}}</h2>
    <!--<p class="w3-opacity"><i>We love music</i></p>-->
    <div>
        <h3>VL Sequence</h3>
        <p class="w3-justify" align="left">{{entry.vlseq.seq}}
        </p>
        <h3>VH Sequence</h3>
        <p class="w3-justify" align="left">{{entry.vhseq.seq}}
        </p>
        <h3 >Metadata</h3>
        <p class="w3-justify" align="left">{{entry.metadata.id}}
        </p>
        {% if entry.metadata.file_name %}
        <embed src="/Users/keithmitchell/Downloads/N358_68.pdf" width="800px" height="2100px" />

            <object data="/Users/keithmitchell/Downloads/N358_68.pdf" type="application/pdf" width="700px" height="700px">
                <embed src=/Users/keithmitchell/Downloads/N358_68.pdf">
                    <p>This browser does not support PDFs. Please download the PDF to view it: <a href="~/Downloads/N358_68.pdf">Download PDF</a>.</p>
                </embed>
            </object>
        {% endif %}

    </div>

</div>


{% endblock %}

trimmer/sequence_db/templates/faq.html
{% extends 'base.html' %}

{% block content %}

<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 90%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

</style>

<!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.17/css/jquery.dataTables.css">-->
<!--<script src="http://code.jquery.com/jquery-1.9.1.js"></script>-->
<!--<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.17/js/jquery.dataTables.js"></script>-->


<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/responsive/1.0.7/js/dataTables.responsive.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/1.0.7/css/responsive.dataTables.min.css">

<script>

$(document).ready(function(){ $('#myTable').DataTable(); });

$(document).ready(function() {
    $('#example').DataTable();
} );
</script>


  <div class="container">
      <h3>What do the category definitions mean?</h3>
        <table id="example" class="display responsive nowrap" cellspacing="0" width="100%" align="center" bgcolor="white" >
      <tr>
          <td><strong>NeuroMab mAbs:</strong></td> <td>sequences obtained from the specific subcloned hybridoma cell lines producing the mAbs that comprise the NeuroMab collection (http://neuromab.ucdavis.edu/neuromabs.cfm)</td>
      </tr>
      <tr>
          <td><strong>Non-NeuroMab mAbs:</strong></td>  <td>sequences obtained from subcloned hybridoma cell lines producing other mAbs that passed multiple validation criteria but that are not part of the NeuroMab collection</td>
      </tr>
      <tr>
          <td><strong>NeuroMab Alternative Subclones:</strong></td> <td>sequences obtained from alternate subcloned hybridoma cell lines producing the mAbs that comprise the NeuroMab collection</td>
      </tr>
      <tr>
          <td>    <strong>Lead oligoclonal Abs:</strong></td> <td>sequences obtained from non-subcloned/oligoclonal hybridoma cell lines producing one or more mAbs that passed multiple validation criteria</td>
      </td>
        <tr>
          <td><strong>Other oligoclonal Abs:</strong></td> <td>sequences obtained from non-subcloned/oligoclonal hybridoma cell lines producing one or more mAbs that passed one or more validation criteria</td>
        </tr>
          <tr>
          <td><strong>Recombinant mAbs:</strong></td> <td>sequences obtained from plasmids expressing validated recombinant mAbs (see Andrews et al., 2019: eLife 8:e43322. PMID: 300667360)</td>
          </tr>
          <tr>
          <td><strong> NeuroMab mAbs:</strong></td> <td>commercially sequenced: sequences independently obtained by outside vendors from the specific subcloned hybridoma cell lines producing the mAbs that comprise the NeuroMab collection</td>
          </tr>
        </table>

      <h3>Why do some entries have more than one light and/or heavy chain sequence?</h3>

    We are displaying any returned sequences that meet the threshold for comprising at least 10% of all Amplicon Sequence Variants (ASVs) from that sample. It is now established that monoclonal hybridomas can express more than one light and/or heavy chain (e.g., Bradbury et al., MABS 10: 539, 2018). Moreover, a subset of these samples are not monoclonal but are oligoclonal, as indicated in the category title. Note that the aberrant light chain sequence derived from SP2/0 myeloma cell partner is not shown.

      <h3>Where is the star system generated and what does it mean?</h3>
    
    <img src="{% static "Equations.png" %}" alt="star system" width="500" height="200">

  </div>


{% endblock %}

trimmer/sequence_db/templates/faq_form.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}
{% block content %}

<style>
#id_question {
    width: 100%;
    height: 100px;
}

#id_message {
    width: 100%;
    height: 200px;
}

#div_id_is_definition {
    padding-left: 20px;
}



</style>
<div class="w3-container w3-content w3-padding-16">
      <h2>Add FAQ</h2>
      <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Submit</button>
      </form>

    {% if user.is_staff %}
    <h4 align="right">Click Delete to Remove the User</h4>
      <div align="right">
              <h4 align="right"><strong>Are you sure you want to delete this FAQ? This will delete all info.</strong></h4>
                  <a href="/delete_faq/{{faq.pk}}/">
                      <button style="height:40px;width:120px;font-size:15px;align:right" label="Delete User" name="so_link" class="btn btn-danger">Delete FAQ</button>
                  </a>
      </div>
  {% endif %}
</div>

<script>
function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "block") {
    x.style.display = "none";
  } else {
    x.style.display = "block";
  }
}
</script>

{% endblock %}

trimmer/sequence_db/templates/signup.html
{% extends 'base.html' %}

{% block javascript %}
  <script>
    $("#id_username").change(function () {
      var username = $(this).val();

      $.ajax({
        url: '/ajax/validate_username/',
        data: {
          'username': username
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert("A user with this username already exists.");
          }
        }
      });

    });
  </script>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}